// app/layout.js or app/layout.tsx
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import { StateProvider } from "@/context/StateContext";
import reducer, { initialState } from "@/context/StateReducers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fiverr Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientLayoutWrapper>
          <div className="relative flex flex-col min-h-screen justify-between">
            <NavBar />
            <main className="flex-grow mt-36">{children}</main>
            <Footer />
          </div>
        </ClientLayoutWrapper>
      </body>
    </html>
  );
}
